### ISSUE TITLE
Use ttf fonts instead of plan9

### ISSUE THREAD

**Issue by i-bsd** [onodera-punpun/melonbar#6]
Any reason why cure.font is being used instead of adding a regular font path to a ttf?

Tried changing plan9font to xgraphics.ParseFont in x.go. It compiled fine but crashes when run.

**Comment by CamilleScholtz** [comment]
The golang ttf drawer doesn't support bitmap fonts, and cure.ttf is a bitmap ttf font. (https://github.com/golang/freetype/issues/52).

I have tried literally all the various font implementations and the plan9 was the best, besides the fact that you manually have to port every font/character, lol.

**Comment by CamilleScholtz** [comment]
Melonbar now uses plan9 fonts, which should be a bit more workable on linux.

**Comment by alexmozaidze** [comment]
So basically, if I want to use different font, I'll need to copy the one I want to `runtime/fonts` directory and edit `fpl` variable in x.go? From what you say here and from the fonts extension in `runtime/fonts` I can assume that I need a bdf format font for it to work properly, but where can I find, for instance, Liberation fonts in bdf format? All of the fonts I have installed are in ttf format.
